version: '3'
services:
  jenkins:
    build: .
    user: root
    image: "jenkins:time-tracker"
    ports:
      - "8081:8080"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - ${HOME}:/home
      - ./jenkins:/var/jenkins_home
